name: TipTester
on: push
  # schedule: 
  # - cron: "0 0 * * *"  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events


jobs:
  TipTester:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'tellor-io/tipper'
    - name: Run test with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - uses: ./../tipper/.github/workflow/action.yml
      with:
        network: "mainnet" #your preference here
        myID: 10 #your preference here
