name: TipTester
on: push
  # schedule: 
  # - cron: "0 0 * * *"  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events


jobs:
  TipTester:
    runs-on: ubuntu-latest
    
    steps:
    - uses: tellor-io/tipper@master
      with:
        network: "mainnet" #your preference here
        myID: 10 #your preference here
